[package]
name = "algorithmic"
version = "0.1.0"
entrypoint = "algorithmic.typ"
authors = ["Jade Lovelace <@lf->", "Pascal Quach <@quachpas>"]
license = "MIT"
description = "Algorithm pseudocode typesetting for Typst, inspired by algorithmicx in LaTeX"
repository = "https://github.com/typst-community/typst-algorithmic"
keywords = ["algorithm", "pseudocode", "procedure"]
categories = ["components", "visualization"]
disciplines = ["computer-science", "mathematics"]
compiler = "0.13.0"
exclude = ["docs", "tests", "tbump.toml", ".gitignore", ".git"]
